### ISSUE TITLE
Error when cloning repo

### ISSUE THREAD

**Issue by oguiza** [ChangWeiTan/MultiRocket#1]
Hi @ChangWeiTan,

First of all thanks a lot for sharing this repo, adding the multivariate multirocket version and for your TSC SOTA. The work you and the rest of the team at Monash are doing is really impressive!

I was planning to start using MultiRocket but I've found an issue when trying to clone the repo. 
When I do: 
```
pip install git+https://github.com/ChangWeiTan/MultiRocket.git
```
I get this error message: 
```
Collecting git+https://github.com/ChangWeiTan/MultiRocket.git
  Cloning https://github.com/ChangWeiTan/MultiRocket.git to /private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-req-build-nmmieyp2
  Running command git clone -q https://github.com/ChangWeiTan/MultiRocket.git /private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-req-build-nmmieyp2
    ERROR: Command errored out with exit status 1:
     command: /Users/nacho/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-req-build-nmmieyp2/setup.py'"'"'; __file__='"'"'/private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-req-build-nmmieyp2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-pip-egg-info-ym4afmr6
         cwd: /private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-req-build-nmmieyp2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/nacho/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/42/4hhwknbd5kzcbq48tmy_gbp00000gn/T/pip-req-build-nmmieyp2/setup.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/ChangWeiTan/MultiRocket.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by baraline** [comment]
Hi @oguiza, 
The error is simply due to the fact that this repository is not a pip package ! If you want to use it on another dataset than those provided in this repository, you'll have to make some custom code to do so !
Most of what you need is located in the multirocket and catch22 folders.

**Comment by oguiza** [comment]
Ok, I'm sorry. I didn't realize that. I'll clone the repo as a normal one, and will close this issue.

**Comment by ChangWeiTan** [comment]
Thanks! do let me know if there is any issue with the code. just updated the multivariate version. @oguiza @baraline
