### ISSUE TITLE
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by Huii** [ChangWeiTan/MultiRocket#4]
I'm attempting to run MultiRocket on some additional data. My pipeline is very similar to the one used in [another scenario](https://github.com/ChangWeiTan/MultiRocket/issues/2).

Unfortunately, this time I do not even get to run my code as the mere import of MultiRocket fails with the following (strange) error messages:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "PathTo\Main.py", line 4, in <module>
    import Algorithms
  File "PathTo\Algorithms.py", line 15, in <module>
    from MuscleData.ANNs import MLP, FCN, ResNet, ROCKET, MINIROCKET, MultiRocket
  File "PathTo\MultiRocket.py", line 1, in <module>
    from PathTo.MultiRocket.multirocket.multirocket import MultiRocket
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 13, in <module>
    from PathTo.MultiRocket.multirocket import minirocket_multivariate as minirocket  # use multivariate version.
  File "PathTo\MultiRocket\multirocket\minirocket_multivariate.py", line 15, in <module>
    fastmath=True, parallel=False, cache=True)
  File "C:\Programs\Anaconda\lib\site-packages\numba\decorators.py", line 186, in wrapper
    disp.compile(sig)
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Programs\Anaconda\lib\site-packages\numba\dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Programs\Anaconda\lib\site-packages\numba\dispatcher.py", line 80, in compile
    raise retval
  File "C:\Programs\Anaconda\lib\site-packages\numba\dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Programs\Anaconda\lib\site-packages\numba\dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 266, in run
    raise patched_exception
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 257, in run
    stage()
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 515, in stage_nopython_frontend
    self.locals)
  File "C:\Programs\Anaconda\lib\site-packages\numba\compiler.py", line 1124, in type_inference_stage
    infer.propagate()
  File "C:\Programs\Anaconda\lib\site-packages\numba\typeinfer.py", line 927, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mCannot unify array(float32, 2d, C) and array(float32, 1d, C) for 'C', defined at PathTo\MultiRocket\multirocket\minirocket_multivariate.py (94)
[1m
File "PathTo\MultiRocket\multirocket\minirocket_multivariate.py", line 94:[0m
[1mdef _fit_biases(X, num_channels_per_combination, channel_indices, dilations, num_features_per_dilation, quantiles):
    <source elided>

[1m            C = C_alpha + C_gamma[index_0] + C_gamma[index_1] + C_gamma[index_2]
[0m            [1m^[0m[0m
[0m
[0m[1m[1] During: typing of assignment at PathTo\MultiRocket\multirocket\minirocket_multivariate.py (95)[0m
[1m
File "PathTo\MultiRocket\multirocket\minirocket_multivariate.py", line 95:[0m
[1mdef _fit_biases(X, num_channels_per_combination, channel_indices, dilations, num_features_per_dilation, quantiles):
    <source elided>
            C = C_alpha + C_gamma[index_0] + C_gamma[index_1] + C_gamma[index_2]
[1m            C = np.sum(C, axis=0)
[0m            [1m^[0m[0m
```

I updated numba to the newest version but I still get the feeling that this might be an issue related with numba. Any help is highly appreciated.

**Comment by ChangWeiTan** [comment]
Does it still run on the [previous scenario](https://github.com/ChangWeiTan/MultiRocket/issues/2)? It should still work on latest numba as I have latest numba version as well.

**Comment by Huii** [comment]
Please close this issue. I was running everything on a separate machine and could solve the issues above by simply reinstalling the Anaconda environment.

**Comment by ChangWeiTan** [comment]
Ok sure. Good luck! Let me know if you need anymore assistance. :)
